name: backend-payment
namespace: backend
replicas: 1
springContainer:
  image: ghcr.io/lgcns-final-lgcms/payment
  version: 0.1
  profile: dev
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
service:
  type: NodePort
  port: 8080
hpa:
  enabled: true
