applications:
  backend-auth:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-auth/configmap.yaml
            - $values/local/backend-auth/secret.yaml
            - $values/local/backend-auth/values.yaml
          valuesObject:
            externalService:
              - name: "valkey-auth-external-service"
                internalPort: 6379
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38122
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-member:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-member/configmap.yaml
            - $values/local/backend-member/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-member-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
              - name: "valkey-member-external-service"
                internalPort: 6379
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38122
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-lecture:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-lecture/configmap.yaml
            - $values/local/backend-lecture/secret.yaml
            - $values/local/backend-lecture/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-lecture-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-core:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-core/configmap.yaml
            - $values/local/backend-core/secret.yaml
            - $values/local/backend-core/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-core-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
              - name: "valkey-core-external-service"
                internalPort: 6379
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38122
                type: ClusterIP
              - name: "kafka-external-service"
                internalPort: 9094
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38123
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-guide:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-guide/configmap.yaml
            - $values/local/backend-guide/secret.yaml
            - $values/local/backend-guide/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-guide-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-lesson:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-lesson/configmap.yaml
            - $values/local/backend-lesson/secret.yaml
            - $values/local/backend-lesson/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-lesson-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-upload:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-upload/configmap.yaml
            - $values/local/backend-upload/secret.yaml
            - $values/local/backend-upload/values.yaml
          valuesObject:
            externalService:
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-consulting:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-consulting/configmap.yaml
            - $values/local/backend-consulting/secret.yaml
            - $values/local/backend-consulting/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-consulting-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
              - name: "valkey-consulting-external-service"
                internalPort: 6379
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38122
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-leveltest:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-leveltest/configmap.yaml
            - $values/local/backend-leveltest/secret.yaml
            - $values/local/backend-leveltest/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-leveltest-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
              - name: "valkey-leveltest-external-service"
                internalPort: 6379
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38122
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-payment:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-payment/configmap.yaml
            - $values/local/backend-payment/secret.yaml
            - $values/local/backend-payment/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-payment-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-streaming:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-streaming/configmap.yaml
            - $values/local/backend-streaming/secret.yaml
            - $values/local/backend-streaming/values.yaml
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-notification:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-notification/configmap.yaml
            - $values/local/backend-notification/secret.yaml
            - $values/local/backend-notification/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-notification-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
              - name: "valkey-notification-external-service"
                internalPort: 6379
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38122
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
