applications:
  backend-auth:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-auth/configmap.yaml
            - $values/local/backend-auth/secret.yaml
            - $values/local/backend-auth/values.yaml
          valuesObject:
            externalService:
              - name: "valkey-auth-external-service"
                internalPort: 6379
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38122
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-member:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-member/configmap.yaml
            - $values/local/backend-member/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-member-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
              - name: "valkey-member-external-service"
                internalPort: 6379
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38122
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-lecture:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-lecture/configmap.yaml
            - $values/local/backend-lecture/secret.yaml
            - $values/local/backend-lecture/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-lecture-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
              - name: "kafka-lecture-external-service"
                internalPort: 9092
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38123
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-core:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-core/configmap.yaml
            - $values/local/backend-core/secret.yaml
            - $values/local/backend-core/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-core-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
              - name: "kafka-core-external-service"
                internalPort: 9092
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38123
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  backend-guide:
    namespace: argocd
    project: default
    sources:
      - chart: spring-chart
        repoURL: https://lgcns-final-lgcms.github.io/infra-helm-packages
        targetRevision: 0.0.4
        helm:
          valueFiles:
            - $values/local/backend-guide/configmap.yaml
            - $values/local/backend-guide/secret.yaml
            - $values/local/backend-guide/values.yaml
          valuesObject:
            externalService:
              - name: "postgres-guide-external-service"
                internalPort: 5432
                externalIp: "localhost" #TODO 개인 로컬 호스트의 NAT IP주소로 변경
                externalPort: 38121
                type: ClusterIP
      - repoURL: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-values.git
        targetRevision: main
        ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
