tempo:
  repository: grafana/tempo
  tag: 2.3.0

persistence:
  enabled: true
  storageClassName: ""
  size: 20Gi
  selector:
    matchLabels:
      name: tempo-pv
securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true

resources:
  requests:
    memory: 128Mi
    cpu: 100m
#  limits:
#    memory: 512Mi
#    cpu: 300m
