config:
  enable: true
  configData: |
    server:
      port: 8080
    spring:
      application:
        name: backend-core
      datasource:
        url: jdbc:postgresql://postgres-core-external-service:5432/core?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
        driver-class-name: org.postgresql.Driver
        hikari:
          connection-test-query: SELECT 1
          validation-timeout: 5000
      jpa:
        show-sql: false
        database: postgresql
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            format_sql: true
      data:
        redis:
          host: valkey-core-external-service
          port: 6379
          database: 15
      kafka:
        bootstrap-servers: kafka-external-service:9094
        template:
          observation-enabled: true
        listener:
          observation-enabled: true
          ack-mode: manual

        consumer:
          group-id: ${spring.application.name}
          key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
          enable-auto-commit: false
          auto-offset-reset: earliest
          max-poll-records: 10
          properties:
            spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
            spring.json.trusted.packages: "*"
            spring.json.use.type.headers: false
            spring.json.value.default.type: com.lgcms.core.common.kafka.dto.KafkaEvent

        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            spring.json.add.type.headers: false
    otel:
      propagators:
        - tracecontext
        - b3
        - baggage
    management:
      otlp:
        tracing:
          endpoint: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317
          transport: grpc
      endpoints:
        web:
          exposure:
            include: prometheus,health,info
      metrics:
        tags:
          application: ${spring.application.name}
      tracing:
        sampling:
          probability: 1.0
        enabled: true
