name: backend-streaming
namespace: backend
replicas: 1
springContainer:
  image: ghcr.io/lgcns-final-lgcms/streaming
  version: 0.2
  profile: dev
  imagePullPolicy: Always
  resources:
    enabled: true
    requests:
      cpu: "2000m"
      memory: "4Gi"
    limits:
      cpu: "4000m"
      memory: "8Gi"
service:
  type: NodePort
  port: 8080
hpa:
  enabled: true
  cpu:
    enabled: true
  memory:
    enabled: true
  behavior:
    enabled: true
monitor:
  enabled: true