apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: tempo
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: tempo-otel
      randomSamplingPercentage: 100
