name: backend-member
namespace: backend
replicas: 1
springContainer:
  image: ghcr.io/lgcns-final-lgcms/member
  version: 0.4
  profile: dev
  imagePullPolicy: Always
  resources:
    enabled: false
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
service:
  type: NodePort
  port: 8080
hpa:
  enabled: false
  cpu:
    enabled: true
  memory:
    enabled: true
  behavior:
    enabled: true