config:
  enable: true
  configData: |
    server:
      port: 8080
    spring:
      datasource:
        url: jdbc:postgresql://postgres-leveltest-external-service:5432/leveltest?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
        driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: false
        database: postgresql
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            format_sql: true
      ai:
        bedrock:
          aws:
            region: ap-northeast-2
          converse:
            chat:
              options:
                model: anthropic.claude-3-haiku-20240307-v1:0

      data:
        redis:
          host: valkey-leveltest-external-service
          port: 6379
          database: 15

      kafka:
        bootstrap-servers: kafka-external-service:9094
