name: backend-leveltest
namespace: backend
replicas: 1
springContainer:
  image: ghcr.io/lgcns-final-lgcms/level-test
  version: 0.3
  profile: dev
  imagePullPolicy: Always
  aws:
    region: "ap-northeast-2"
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
service:
  type: NodePort
  port: 8080
hpa:
  enabled: true
