name: backend-lesson
namespace: backend
replicas: 1
springContainer:
  image: ghcr.io/lgcns-final-lgcms/lesson
  version: 0.6
  profile: dev
  imagePullPolicy: Always
  resources:
    enabled: true
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
service:
  type: NodePort
  port: 8080
hpa:
  enabled: true
  cpu:
    enabled: true
  memory:
    enabled: true
  behavior:
    enabled: true
monitor:
  enabled: true