apiVersion: v1
kind: Secret
metadata:
  name: my-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  url: aHR0cHM6Ly9naXRodWIuY29tL0xHQ05TLUZJTkFMLUxHQ01TL2luZnJhLWhlbG0tdmFsdWVzLmdpdA==
  type: Z2l0
  username: amFld29uTGVlS09S
  password: Z2hwXzhHeUlMd1hDQlVOaHpCamhhbnFxQW45QVVJd3dFUDJZdkZjeQ==
# echo -n "인코딩할_값" | base64