config:
  enable: true
  configData: |
    server:
      port: 8080
    
    spring:
      application:
        name: backend-streaming
    
      servlet:
        multipart:
          max-file-size: 1200MB
          max-request-size: 1200MB
    
      kafka:
        bootstrap-servers: kafka-external-service:9094
    
        listener:
          ack-mode: manual_immediate
    
        consumer:
          group-id: ${spring.application.name}
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          enable-auto-commit: false
          auto-offset-reset: latest
          max-poll-records: 10
          properties:
            spring.json.trusted.packages: "*"
            spring.json.use.type.headers: false
    
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            spring.json.add.type.headers: false
    cloud:
      aws:
        region:
          auto: false
        stack:
          auto: false
    ffmpeg:
      path: /usr/bin/ffmpeg
    ffprobe:
      path: /usr/bin/ffprobe
    management:
      endpoints:
        web:
          exposure:
            include: prometheus,health,info
    metrics:
      tags:
        application: ${spring.application.name}
