name: backend-consulting
namespace: backend
replicas: 1
springContainer:
  image: ghcr.io/lgcns-final-lgcms/consulting
  version: 0.2
  profile: dev
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  aws:
    region: "ap-northeast-2"
service:
  type: NodePort
  port: 8080
hpa:
  enabled: true
  cpu:
    enabled: true
  memory:
    enabled: true
  behavior:
    enabled: true
